##### Задание 1. Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = np.array ([[1, 6], 
               [2, 8],
               [3, 11],
               [3, 10],
               [1, 7]], dtype = float)

In [4]:
mean_a = a.mean(axis = 0).copy()
print(mean_a)

[2.  8.4]


#### Задание 2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [75]:
a_centered = (a - mean_a).copy()
print("Результат вычисления: \n {}" . format(a_centered))

Результат вычисления: 
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


#### Задание 3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [81]:
c = a_centered[0:, 0].copy()
print('Первый столбец: \n', c)
d = a_centered [0: , 1].copy()
print('Второй столбец: \n', d)
a_centered_sp = c.dot(d)
print('Скалярное произведение: \n', a_centered_sp)
f = a.shape
g = print('Результат деления: \n', a_centered_sp / (f[0]-1))

Первый столбец: 
 [-1.  0.  1.  1. -1.]
Второй столбец: 
 [-2.4 -0.4  2.6  1.6 -1.4]
Скалярное произведение: 
 8.0
Результат деления: 
 2.0


#### Задание 4. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [82]:
a_T = a.T
print(a_T)

[[ 1.  2.  3.  3.  1.]
 [ 6.  8. 11. 10.  7.]]


In [85]:
h = np.cov(a_T)
print(h[0, 1])


2.0
