#### Задание 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np
a = np.arange(12, 24)
print('Заданный массив: {}'.format(a))

Заданный массив: [12 13 14 15 16 17 18 19 20 21 22 23]


#### Задание 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [16]:
print('Массив b: {}'  .format(a.reshape(2, 6)))
print('Массив c: {}'.format(a.reshape(3, 4)))
print('Массив d: {}'.format(a.reshape(4, 3)))
print('Массив e: {}'.format(a.reshape(6, 2)))
print('Массив f: {}'.format(a.reshape(12, 1)))

Массив b: [[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив c: [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив d: [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив e: [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив f: [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [26]:
print('Массив b:{}'.format(a.reshape(2, -1)))
print('Массив c:{}'.format(a.reshape(3, -1)))
print('Массив d:{}'.format(a.reshape(4, -1)))
print('Массив e:{}'.format(a.reshape(-1, 2)))
print('Массив f:{}'.format(a.reshape(-1, 1)))

Массив b:[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив c:[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив d:[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив e:[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив f:[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Задание 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
нет

#### Задание 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив

In [51]:
a = np.random.randn(3, 4)
print('Массив: {}'.format(a))
print(a.size)
c = a.flatten()
print('Одномерный массив: {}'.format(c))
print(c.size)

Массив: [[-0.47495103 -1.18541358  0.90465834  0.20776258]
 [ 1.56451995 -0.47411606 -0.49521076 -1.1271858 ]
 [ 0.39088138 -0.18620786  0.72639707  0.20472984]]
12
Одномерный массив: [-0.47495103 -1.18541358  0.90465834  0.20776258  1.56451995 -0.47411606
 -0.49521076 -1.1271858   0.39088138 -0.18620786  0.72639707  0.20472984]
12


#### Задание 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [6]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


#### Задание 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [9]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [10]:
np.array_equal(a, b)

True

нет разницы. Одинаковы

#### Задание 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10

In [19]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print(v)
print(a.size + b.size)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


10

#### Задание 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [33]:
a = np.arange(12)
print('Одномерный массив a:{}'.format(a))
A = a.reshape(4, 3)
print('Матрица А (4х3):{}'.format(A))
#A = np.reshape((a, (4, 3))
A_T = A.T
print('Обратная матрица А_Т:{}'.format(A_T))
B = A.dot(A_T)
print('Матрица произведения АхА_Т:{}'.format(B))
np.linalg.det(B)

Одномерный массив a:[ 0  1  2  3  4  5  6  7  8  9 10 11]
Матрица А (4х3):[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Обратная матрица А_Т:[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
Матрица произведения АхА_Т:[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


0.0

определитель матрицы В равен нулю, соответственно обратной матрицы не существует

#### Задание 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [13]:
c = np.random.seed(42)

#### Задание 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [28]:
c = np.random.randint(0, 16, (1, 16))
print(c)

[[13 13 14 13  2 11  6  3 15  8  2  4  2  6  4  8]]


#### Задание 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D

In [29]:
C = c.reshape(4, 4)
print(C)
#c = np.random.choise(A, (1, 16))

[[13 13 14 13]
 [ 2 11  6  3]
 [15  8  2  4]
 [ 2  6  4  8]]


In [31]:
C = C * 10
print(C)

[[1300 1300 1400 1300]
 [ 200 1100  600  300]
 [1500  800  200  400]
 [ 200  600  400  800]]


In [34]:
D = C + B
print(D)

[[1305 1314 1423 1332]
 [ 214 1150  686  422]
 [1523  886  349  612]
 [ 232  722  612 1102]]


In [35]:
d = np.linalg.det(D)
print('Определитель матрицы D:{}'.format(d))

Определитель матрицы D:-803941840000.0007


In [36]:
r = np.linalg.matrix_rank(D)
print('Ранг матрицы D:{}'.format(r))

Ранг матрицы D:4


In [41]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.00028935 -0.00044876  0.00054492 -0.00048052]
 [-0.00086154  0.00129294  0.00051708  0.00025907]
 [ 0.00158611 -0.00016216 -0.00115109 -0.00121579]
 [-0.00037731 -0.00066257  0.00018577  0.00151406]]


#### Задание 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [44]:
index = np.where(D_inv < 0)
D_inv[index] = 0
print(D_inv)
index = np.where(D_inv > 0)
D_inv[index] = 1
print(D_inv)

[[0.00028935 0.         0.00054492 0.        ]
 [0.         0.00129294 0.00051708 0.00025907]
 [0.00158611 0.         0.         0.        ]
 [0.         0.         0.00018577 0.00151406]]
[[1. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]]


In [45]:
E = D_inv.copy()
print(E)

[[1. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]]


In [48]:
E = np.where(D_inv, B, C)
print(E)

[[   5 1300   23 1300]
 [ 200   50   86  122]
 [  23  800  200  400]
 [ 200  600  212  302]]
